// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
      /**
       * OpenDialog
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenDialog": () => {
        return window.go.main.App.OpenDialog();
      },
      /**
       * OpenDirectory
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenDirectory": () => {
        return window.go.main.App.OpenDirectory();
      },
      /**
       * OpenFile
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "OpenFile": (arg1) => {
        return window.go.main.App.OpenFile(arg1);
      },
      /**
       * ReceiveFile
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "ReceiveFile": (arg1) => {
        return window.go.main.App.ReceiveFile(arg1);
      },
      /**
       * SendFile
       * @returns {Promise<void>} 
       */
      "SendFile": () => {
        return window.go.main.App.SendFile();
      },
      /**
       * UpdateSendProgress
       * @param {number} arg1 - Go Type: int64
       * @param {number} arg2 - Go Type: int64
       * @returns {Promise<void>} 
       */
      "UpdateSendProgress": (arg1, arg2) => {
        return window.go.main.App.UpdateSendProgress(arg1, arg2);
      },
    },
  },

};
export default go;
