// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * AppInstalledFromPackageManager
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "AppInstalledFromPackageManager": () => {
        return window.go.main.App.AppInstalledFromPackageManager();
      },
      /**
       * CancelWormholeRequest
       * @returns {Promise<void>} 
       */
      "CancelWormholeRequest": () => {
        return window.go.main.App.CancelWormholeRequest();
      },
      /**
       * ClearSelectedFiles
       * @returns {Promise<void>} 
       */
      "ClearSelectedFiles": () => {
        return window.go.main.App.ClearSelectedFiles();
      },
      /**
       * GetCurrentVersion
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetCurrentVersion": () => {
        return window.go.main.App.GetCurrentVersion();
      },
      /**
       * GetLogPath
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetLogPath": () => {
        return window.go.main.App.GetLogPath();
      },
      /**
       * GetReceivedFile
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetReceivedFile": () => {
        return window.go.main.App.GetReceivedFile();
      },
      /**
       * GetSelectedFiles
       * @returns {Promise<Array<string>>}  - Go Type: []string
       */
      "GetSelectedFiles": () => {
        return window.go.main.App.GetSelectedFiles();
      },
      /**
       * GetUserPrefs
       * @returns {Promise<UserSettings>}  - Go Type: settings.UserSettings
       */
      "GetUserPrefs": () => {
        return window.go.main.App.GetUserPrefs();
      },
      /**
       * OpenDirectoryDialog
       * @returns {Promise<Array<string>|Error>}  - Go Type: []string
       */
      "OpenDirectoryDialog": () => {
        return window.go.main.App.OpenDirectoryDialog();
      },
      /**
       * OpenFile
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "OpenFile": (arg1) => {
        return window.go.main.App.OpenFile(arg1);
      },
      /**
       * OpenFilesDialog
       * @returns {Promise<Array<string>|Error>}  - Go Type: []string
       */
      "OpenFilesDialog": () => {
        return window.go.main.App.OpenFilesDialog();
      },
      /**
       * PersistUserSettings
       * @returns {Promise<void>} 
       */
      "PersistUserSettings": () => {
        return window.go.main.App.PersistUserSettings();
      },
      /**
       * ReceiveFile
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "ReceiveFile": (arg1) => {
        return window.go.main.App.ReceiveFile(arg1);
      },
      /**
       * SelectedFilesSend
       * @returns {Promise<void>} 
       */
      "SelectedFilesSend": () => {
        return window.go.main.App.SelectedFilesSend();
      },
      /**
       * SendDirectory
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SendDirectory": (arg1) => {
        return window.go.main.App.SendDirectory(arg1);
      },
      /**
       * SendFile
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "SendFile": (arg1) => {
        return window.go.main.App.SendFile(arg1);
      },
      /**
       * SetDownloadsFolder
       * @returns {Promise<string>}  - Go Type: string
       */
      "SetDownloadsFolder": () => {
        return window.go.main.App.SetDownloadsFolder();
      },
      /**
       * SetNotificationsParam
       * @param {boolean} arg1 - Go Type: bool
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "SetNotificationsParam": (arg1) => {
        return window.go.main.App.SetNotificationsParam(arg1);
      },
      /**
       * SetOverwriteParam
       * @param {boolean} arg1 - Go Type: bool
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "SetOverwriteParam": (arg1) => {
        return window.go.main.App.SetOverwriteParam(arg1);
      },
      /**
       * SetSelfUpdateParam
       * @param {boolean} arg1 - Go Type: bool
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "SetSelfUpdateParam": (arg1) => {
        return window.go.main.App.SetSelfUpdateParam(arg1);
      },
      /**
       * ShowErrorDialog
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<void>} 
       */
      "ShowErrorDialog": (arg1) => {
        return window.go.main.App.ShowErrorDialog(arg1);
      },
      /**
       * UpdateCheckUI
       * @returns {Promise<void>} 
       */
      "UpdateCheckUI": () => {
        return window.go.main.App.UpdateCheckUI();
      },
      /**
       * UpdateSendProgress
       * @param {number} arg1 - Go Type: int64
       * @param {number} arg2 - Go Type: int64
       * @returns {Promise<void>} 
       */
      "UpdateSendProgress": (arg1, arg2) => {
        return window.go.main.App.UpdateSendProgress(arg1, arg2);
      },
      /**
       * VerifyNotificationIcon
       * @returns {Promise<string>}  - Go Type: string
       */
      "VerifyNotificationIcon": () => {
        return window.go.main.App.VerifyNotificationIcon();
      },
    },
  },

};
export default go;
