// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ShowErrorDialog(arg1) {
  window['go']['main']['App']['ShowErrorDialog'](arg1);
}

export function UpdateSendProgress(arg1, arg2) {
  window['go']['main']['App']['UpdateSendProgress'](arg1, arg2);
}

export function AppInstalledFromPackageManager() {
  return window['go']['main']['App']['AppInstalledFromPackageManager']();
}

export function SetOverwriteParam(arg1) {
  return window['go']['main']['App']['SetOverwriteParam'](arg1);
}

export function GetUserPrefs() {
  return window['go']['main']['App']['GetUserPrefs']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function ReceiveFile(arg1) {
  window['go']['main']['App']['ReceiveFile'](arg1);
}

export function SetNotificationsParam(arg1) {
  return window['go']['main']['App']['SetNotificationsParam'](arg1);
}

export function VerifyNotificationIcon() {
  return window['go']['main']['App']['VerifyNotificationIcon']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetReceivedFile() {
  return window['go']['main']['App']['GetReceivedFile']();
}

export function SendFile(arg1) {
  window['go']['main']['App']['SendFile'](arg1);
}

export function SetDownloadsFolder() {
  return window['go']['main']['App']['SetDownloadsFolder']();
}

export function GetSelectedFiles() {
  return window['go']['main']['App']['GetSelectedFiles']();
}

export function PersistUserSettings() {
  window['go']['main']['App']['PersistUserSettings']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function OpenFile(arg1) {
  window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFilesDialog() {
  return window['go']['main']['App']['OpenFilesDialog']();
}

export function SelectedFilesSend() {
  window['go']['main']['App']['SelectedFilesSend']();
}

export function SendDirectory(arg1) {
  window['go']['main']['App']['SendDirectory'](arg1);
}

export function SetSelfUpdateParam(arg1) {
  return window['go']['main']['App']['SetSelfUpdateParam'](arg1);
}

export function CancelWormholeRequest() {
  window['go']['main']['App']['CancelWormholeRequest']();
}

export function ClearSelectedFiles() {
  window['go']['main']['App']['ClearSelectedFiles']();
}

export function UpdateCheckUI() {
  window['go']['main']['App']['UpdateCheckUI']();
}
